spring:
  application:
    name: jwt

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}/jwt?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  refresh:
    secret:
      key: ${JWT_REFRESH_SECRET_KEY}